chore(fee): Increase transaction fees
peaqnetwork/peaq-network-node pull request #223
Opened 2024-04-24 11:27 UTC by DocteurPing

This PR is linked to [this task](https://app.asana.com/0/1201590612941071/1206391010680680). The goal of this PR is to increase the fee on the different chains.

2024-04-24 14:14 UTC, sfffaaa requested changes
According to the Asana task, we also need to change TransactionByteFee.

2024-04-24 14:14 UTC, sfffaaa commented on runtime/krest/src/lib.rs
> +		let p = MILLICENTS * 54000;
Hmmm, would you mind to explain this?

2024-05-10 10:30 UTC, lavish0000 approved these changes

2024-05-10 10:37 UTC, sfffaaa approved these changes

2024-05-10 11:39 UTC, merged