Feat/1201590612941071 krest 0.9.29
peaqnetwork/peaq-network-node pull request #66
Opened 2022-12-02 16:42 UTC by sfffaaa

1. Add Krest runtime
2. Add Krest genensis file
3. Limit the collator/delegator extrinsic
4. Add utility pallet to Krest network

2022-12-06 13:57 UTC, irediaes requested changes

2022-12-06 13:57 UTC, irediaes commented on node/src/command.rs
> +				})
Too many if-else. We can improve this code. Probably make it a single function that implement the unique call as closures

2022-12-06 21:16 UTC, sfffaaa commented on node/src/command.rs
> +				})
Refined it, please take a look

2022-12-07 10:56 UTC, irediaes approved these changes

2022-12-07 11:15 UTC, merged